name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: aaed5883e6f945381b9f1356e05433a4
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
