name: Latest blog posts workflow (Syntackle)
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every hour, on the 0th min
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in hashnode posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          commit_message: "updated: fetched and updated `readme.md` with latest blog posts"
          feed_list: "https://karankeyash.hashnode.dev/rss.xml"
          disable_sort: true
          max_post_count: 5
          date_format: "mmm d, yyyy"
